/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FoodItem {
  'id' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'price' : number,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'createdAt' : bigint,
  'totalAmount' : number,
  'address' : string,
  'phone' : string,
  'items' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createFoodItem' : ActorMethod<[FoodItem], bigint>,
  'createOrder' : ActorMethod<[Order], bigint>,
  'deleteFoodItem' : ActorMethod<[bigint], FoodItem>,
  'filterFoodItemsByCategory' : ActorMethod<[string], Array<FoodItem>>,
  'getAllFoodItems' : ActorMethod<[], Array<FoodItem>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFoodItem' : ActorMethod<[bigint], FoodItem>,
  'getOrder' : ActorMethod<[bigint], Order>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateFoodItem' : ActorMethod<[FoodItem], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, string], Order>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];