/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FoodItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'createdAt' : IDL.Int,
  'totalAmount' : IDL.Float64,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'items' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createFoodItem' : IDL.Func([FoodItem], [IDL.Nat], []),
  'createOrder' : IDL.Func([Order], [IDL.Nat], []),
  'deleteFoodItem' : IDL.Func([IDL.Nat], [FoodItem], []),
  'filterFoodItemsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FoodItem)],
      ['query'],
    ),
  'getAllFoodItems' : IDL.Func([], [IDL.Vec(FoodItem)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFoodItem' : IDL.Func([IDL.Nat], [FoodItem], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateFoodItem' : IDL.Func([FoodItem], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [Order], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FoodItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'createdAt' : IDL.Int,
    'totalAmount' : IDL.Float64,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'items' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createFoodItem' : IDL.Func([FoodItem], [IDL.Nat], []),
    'createOrder' : IDL.Func([Order], [IDL.Nat], []),
    'deleteFoodItem' : IDL.Func([IDL.Nat], [FoodItem], []),
    'filterFoodItemsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FoodItem)],
        ['query'],
      ),
    'getAllFoodItems' : IDL.Func([], [IDL.Vec(FoodItem)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFoodItem' : IDL.Func([IDL.Nat], [FoodItem], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateFoodItem' : IDL.Func([FoodItem], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [Order], []),
  });
};

export const init = ({ IDL }) => { return []; };